# -*- coding: utf-8 -*-
"""Lab6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wK5bNpH1klGOk_ihmmBgxyg5dylvWqYU
"""

!head -n 1 data.csv

import numpy as np
#Пункт 1
dt = np.dtype([
    ('ts', 'i4'),
    ('acc_id', 'i2'),
    ('likes', 'u4'),
    ('shares', 'u2'),
    ('com', 'u2'),
    ('sent', 'f4')
])

data = np.genfromtxt('data.csv', delimiter=',', dtype=dt, skip_header=1)

n_rows = len(data)
mem_bytes = data.nbytes
mem_mb = mem_bytes / (1024**2)
print(f"Строк: {n_rows}, Память: {mem_mb:.2f} мегабайт")

nan_count = 0
inf_count = 0
for field in data.dtype.names:
    if np.issubdtype(data.dtype[field], np.floating):
        nan_count += np.sum(np.isnan(data[field]))
        inf_count += np.sum(np.isinf(data[field]))

total_anomalies = nan_count + inf_count
total_elements = n_rows * len(data.dtype.names)
print(nan_count/len(data), inf_count/len(data))
if total_anomalies / total_elements > 0.03:
    print("Доля NaN/Inf превышает 3%!")
np.save('data2.npy', data)

#Пункт 2
data2 = np.load('data2.npy')

mask_likes = data2['likes'] < 0
mask_sent = (data2['sent'] < -1) | (data2['sent'] > 1)
q99_com = np.percentile(data2['com'], 75)
mask_com = data2['com'] > q99_com

mask_anomaly = mask_likes | mask_sent | mask_com
count_anomaly = np.count_nonzero(mask_anomaly)
percent_anomaly = count_anomaly / len(data2) * 100
print(f"Аномальных строк: {count_anomaly} ({percent_anomaly:.2f}%)")

data2['likes'] = np.where(data2['likes'] < 0, 0, data2['likes'])
data2['sent'] = np.clip(data2['sent'], -1, 1)
print(data2['sent'][:5])
data2['com'] = np.clip(data2['com'], 0, q99_com)
print(f"Диапазон sent: [{np.nanmin(data2['sent'])}, {np.nanmax(data2['sent'])}]")

data2['sent'] = np.where(np.isnan(data2['sent']), 0.0, data2['sent'])

acc_ids, inv_idx = np.unique(data2['acc_id'], return_inverse=True)
n_groups = len(acc_ids)

sum_likes = np.zeros(n_groups, dtype=np.int64)
sum_sent = np.zeros(n_groups, dtype=np.float64)
count_sent = np.zeros(n_groups, dtype=np.int32)

np.add.at(sum_likes, inv_idx, data2['likes'])
np.add.at(sum_sent, inv_idx, data2['sent'])
np.add.at(count_sent, inv_idx, 1)
print(data2['sent'][inv_idx[2]])

mean_sent_group = np.divide(sum_sent, count_sent, out=np.zeros_like(sum_sent), where=count_sent > 0)

sq_diff = (data2['sent'] - mean_sent_group[inv_idx]) ** 2
var_sum = np.zeros(n_groups, dtype=np.float64)
np.add.at(var_sum, inv_idx, sq_diff)

std_sent_group = np.zeros(n_groups, dtype=np.float32)
valid_std = count_sent > 1
std_sent_group[valid_std] = np.sqrt(var_sum[valid_std] / (count_sent[valid_std] - 1))

z_sent = np.zeros(len(data2), dtype=np.float32)
valid_z = std_sent_group[inv_idx] > 1e-8
z_sent[valid_z] = (data2['sent'][valid_z] - mean_sent_group[inv_idx][valid_z]) / std_sent_group[inv_idx][valid_z]

print(std_sent_group)
print(z_sent)

#Пункт 3, который перед 4
k = 60
cumsum_likes = np.cumsum(data2['likes'])
moving_sum = np.zeros(len(data2), dtype=np.int64)
moving_sum[k-1:] = cumsum_likes[k-1:] - np.concatenate(([0], cumsum_likes[:-k]))

diff_shares = np.diff(data2['shares'])
diff_shares = np.concatenate(([0], diff_shares))
#Пункт Первый признак
new_dtype = np.dtype(data2.dtype.descr + [('virality', 'i4')])
data3 = np.zeros(len(data2), dtype=new_dtype)

for field_name in data2.dtype.names:
    data3[field_name] = data2[field_name]
data3['virality'] = diff_shares

print(f"Поля в data3: {data3.dtype.names}")
print(f"Размер moving_sum: {moving_sum.shape}")
print(f"Размер diff_shares: {diff_shares.shape}")
print(f"Новый размер data3: {data3.shape}")

#Пункт 4 второй признак
total_activity = data3['likes'] + data3['shares'] + data3['com']
like_ratio = np.where(total_activity > 0, data3['likes'] / total_activity, 0)

mask_bad = ~np.isfinite(like_ratio)
like_ratio[mask_bad] = 0

new_dtype_6 = np.dtype(data3.dtype.descr + [('like_ratio', 'f4')])
data4 = np.zeros(len(data3), dtype=new_dtype_6)

for field_name in data3.dtype.names:
    data4[field_name] = data3[field_name]
data4['like_ratio'] = like_ratio

print(f"Поля data4: {data4.dtype.names}")
print(f"Среднее среди всех соотношений лайков к активностям: {np.mean(data4['like_ratio']):.4f}")

#Пункт 5
mask_cond = data4['sent'] > 0
group_stats = np.zeros((n_groups, 3), dtype=np.float32)

for i in range(n_groups):
    group_mask = (inv_idx == i) & mask_cond
    if np.any(group_mask):
        values = data4['likes'][group_mask]
        mean_val = np.mean(values)
        median_val = np.median(values)
        p90_val = np.percentile(values, 90)
    else:
        mean_val, median_val, p90_val = 0.0, 0.0, 0.0
    group_stats[i] = [acc_ids[i], mean_val, median_val]
print(f"Shape group_stats: {group_stats.shape}")
print("Первые 10 групп (id, mean, median):")
print(group_stats[:10])

#Пункт 6
lag_shares = np.roll(data4['shares'], shift=1)
lag_shares[0] = 0

diff_lag = data4['shares'] - lag_shares
signs = np.sign(diff_lag)
counts = np.bincount(signs + 1)

print(f"Упало: {counts[0]} записей")
print(f"0: {counts[1]} записей")
print(f"Выросло: {counts[2]} записей\n")

total = len(diff_lag)
percent_up = counts[2] / total * 100
print(f"Доля публикаций с ростом репостов: {percent_up:.2f}%")

#Пункт 7
rep_count = np.zeros(n_groups, dtype=np.int32)
likes_clean = data4['likes'].copy()

for i in range(n_groups):
    group_mask = (inv_idx == i)
    group_values = likes_clean[group_mask]
    if len(group_values) < 4:
        continue

    q1 = np.percentile(group_values, 25)
    q3 = np.percentile(group_values, 75)
    iqr = q3 - q1

    lower = q1 - 1.5 * iqr
    upper = q3 + 1.5 * iqr
    median_val = np.median(group_values)

    outlier_mask = (group_values < lower) | (group_values > upper)
    n_replaced = np.sum(outlier_mask)
    rep_count[i] = n_replaced

    if n_replaced > 0:
        global_indices = np.where(group_mask)[0]
        likes_clean[global_indices[outlier_mask]] = median_val

data4['likes'] = likes_clean

total_replaced = np.sum(rep_count)
percent_replaced = total_replaced / len(likes_clean) * 100
print(f"Всего заменено: {total_replaced} ({percent_replaced:.2f}%)")
print(f"Максимум замен в группе: {np.max(rep_count)}")
print(f"Групп с заменами: {np.sum(rep_count > 0)} из {n_groups}")

#Пункт 8
mask_ts = data4['ts'] <= 0
mask_acc = data4['acc_id'] <= 0
mask_sent_logic = (data4['likes'] + data4['shares'] + data4['com'] == 0) & (np.abs(data4['sent']) > 0.5)

mask_violations = mask_ts | mask_acc | mask_sent_logic
n_violations = np.sum(mask_violations)
percent_violations = n_violations / len(data4) * 100
print(f"Всего нарушений логики: {n_violations} ({percent_violations:.2f}%)\n")

print("Примеры нарушающих строк:")
print(data4[mask_violations][:3])

data4['sent'] = np.where(mask_sent_logic, 0.0, data4['sent'])

n_after_sent = np.sum((data4['likes'] + data4['shares'] + data4['com'] == 0) & (np.abs(data4['sent']) > 1e-5))
print(f"Осталось нарушений sent после исправления: {n_after_sent}")

#Пункт 9 сжатие
unique_cats, counts = np.unique(data4['sent'], return_counts=True)
threshold = int(len(data4) * 0.01)

rare_mask = counts < threshold
rare_cats = unique_cats[rare_mask]
print(f"Найдено редких категорий: {len(rare_cats)} из {len(unique_cats)}")

mask_replace = np.isin(data4['sent'], rare_cats)
data4['sent'] = np.where(mask_replace, 0, data4['sent'])

new_unique, new_counts = np.unique(data4['sent'], return_counts=True)
count_other = int(new_counts[new_unique == 0][0]) if 0 in new_unique else 0
percent_other = count_other / len(data4) * 100

print(f"Уникальных категорий после сжатия: {len(new_unique)}")
print(f"Доля категории other: {percent_other:.2f}%")
if len(new_unique) > 1:
    print(f"Топ-3 самых частых аккаунта: {list(zip(new_unique[1:4], new_counts[1:4]))}")
else:
    print("Все категории перешли в other")

np.save('data_final.npy', data4)
print(data4.columns)